import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { closeSync, openSync } from "node:fs";
import { readFile, writeFile, chmod } from "node:fs/promises";
import { basename, join } from "node:path";
import { LOG_DIR } from "./config.mjs";
import { writeState, readState, profileDir } from "./profiles.mjs";
import { backendFor, backendBinaryFor } from "./backends.mjs";
import { computeFlags } from "./autodetect.mjs";
import { findOmlx } from "./omlx-runtime.mjs";
import { pc } from "./ui.mjs";

const execFileAsync = promisify(execFile);

// ── Compute server command from profile config ─────────────────────────────
// Single source of truth: derives the full command (binary + args + env) from
// the profile's stored configuration.  Used for both launching and display so
// they always match.  No stored commandArgv — the command is always fresh.

export async function computeServerCommand(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") return null;

  const binary = await backendBinaryFor(profile.backend);
  if (!binary) throw new Error("Server binary not found. Run offgrid-ai interactively to install.");

  // llama-cpp
  const result = computeFlags(
    profile.capabilities ?? {},
    profile.modelPath,
    profile.mmprojPath,
    profile.drafterPath,
    profile.flags ?? {},
  );

  return { binary, argv: result.argv, extraEnv: {}, backend };
}

/** Build a runnable start.sh script for the profile. */
export function buildStartScript(profile, command) {
  const { binary, argv, extraEnv } = command;
  const backend = backendFor(profile.backend);
  const lines = [
    "#!/bin/bash",
    `# Generated by offgrid-ai — do not edit`,
    `# Profile: ${profile.label}`,
    `# Backend: ${backend.label}`,
  ];
  for (const [key, value] of Object.entries(extraEnv)) {
    lines.push(`export ${key}="${value}"`);
  }
  lines.push(""); // blank line before exec
  // Format the exec command with backslash continuation
  lines.push(`exec ${quoteShell(binary)} \\`);
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    const hasValue = arg.startsWith("--") && next && !next.startsWith("--");
    if (hasValue) {
      lines.push(`  ${arg} ${quoteShell(next)}${i + 2 < argv.length ? " \\" : ""}`);
      i += 1;
    } else {
      lines.push(`  ${arg}${i + 1 < argv.length ? " \\" : ""}`);
    }
  }
  return lines.join("\n") + "\n";
}

// ── Start server ───────────────────────────────────────────────────────────

export async function startServer(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") {
    return startManagedServer(profile, backend);
  }
  return startLocalServer(profile);
}

async function startLocalServer(profile) {
  const command = await computeServerCommand(profile);
  if (!command) throw new Error("No server command for this backend.");

  const { binary, argv, extraEnv } = command;

  const timestamp = timestampForFile();
  const rawLogPath = join(LOG_DIR, `${profile.id}-${timestamp}.raw.log`);
  const friendlyLogPath = join(LOG_DIR, `${profile.id}-${timestamp}.friendly.log`);

  // Write start.sh so the user can run the model manually
  const scriptPath = join(profileDir(profile.id), "start.sh");
  await writeFile(scriptPath, buildStartScript(profile, command), "utf8");
  await chmod(scriptPath, 0o755);

  await writeFile(rawLogPath, `[offgrid-ai] ${new Date().toISOString()}\n[binary] ${binary}\n[argv]\n${argv.join(" ")}\n`, "utf8");
  await writeFile(friendlyLogPath, `[launch] starting ${backendFor(profile.backend).label} for ${profile.label}\n`, "utf8");

  const env = { ...process.env, ...extraEnv };

  const rawFd = openSync(rawLogPath, "a");
  let child;
  try {
    child = spawn(binary, argv, { detached: true, stdio: ["ignore", rawFd, rawFd], env });
  } finally {
    closeSync(rawFd);
  }
  child.unref();

  const state = {
    pid: child.pid,
    profileId: profile.id,
    baseUrl: profile.baseUrl,
    binary,
    rawLogPath,
    friendlyLogPath,
    startedAt: new Date().toISOString(),
  };
  await writeState(profile.id, state);
  return state;
}

async function startManagedServer(profile, backend) {
  if (await serverReady(profile.baseUrl)) {
    // Apply per-model settings (MTP) even when server is already running.
    if (backend.id === "omlx" && profile.capabilities?.mtp) {
      await ensureOmlxMtpSetting(profile);
    }
    return writeManagedState(profile, backend);
  }

  // Try to start the managed server via CLI
  if (backend.id === "omlx") {
    try {
      const omlxBin = await findOmlx();
      if (!omlxBin) {
        throw new Error(`${backend.label} is not installed. Run offgrid-ai to install it, or install manually: brew tap jundot/omlx && brew install omlx`);
      }
      await execFileAsync(omlxBin, ["start"], { timeout: 10000 });
    } catch (err) {
      if (err.message.includes("not installed")) throw err;
      throw new Error(`${backend.label} could not be auto-started: ${err.message}. Run \`omlx start\` manually.`, { cause: err });
    }
  }

  // Wait for it to come up
  for (let i = 0; i < 60; i++) {
    await sleep(2000);
    if (await serverReady(profile.baseUrl)) break;
    process.stdout.write(".");
  }
  if (!(await serverReady(profile.baseUrl))) {
    throw new Error(`${backend.label} is not responding at ${profile.baseUrl}. Start it and try again.`);
  }

  // Apply per-model settings (MTP) before the model is loaded.
  // oMLX applies MTP patches at load time, so the setting must be in
  // model_settings.json before any request triggers a load.
  if (backend.id === "omlx" && profile.capabilities?.mtp) {
    await ensureOmlxMtpSetting(profile);
  }

  return writeManagedState(profile, backend);
}

/**
 * Enable MTP on an oMLX model via the admin API before loading.
 * oMLX applies MTP patches at model load time, so the setting must be
 * persisted to model_settings.json before any request triggers a load.
 * If the model is already loaded, oMLX will use the setting on next reload.
 */
async function ensureOmlxMtpSetting(profile) {
  const baseUrl = profile.baseUrl?.replace(/\/v1\/?$/u, "") || "";
  const modelId = profile.omlxModel ?? profile.modelAlias ?? profile.id;
  try {
    const response = await fetch(`${baseUrl}/admin/api/models/${encodeURIComponent(modelId)}/settings`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ mtp_enabled: true }),
      signal: AbortSignal.timeout(5000),
    });
    if (response.ok) {
      console.log(pc.green(`[mtp] Enabled MTP speculative decoding for ${modelId}`));
    } else if (response.status === 401 || response.status === 403) {
      console.log(pc.yellow(`[mtp] Could not enable MTP: oMLX admin authentication required. Enable skip_api_key_verification in oMLX settings, or enable MTP manually from the admin panel.`));
    } else if (response.status === 404) {
      console.log(pc.yellow(`[mtp] Model ${modelId} not found on oMLX server. MTP setting not applied.`));
    } else {
      const detail = await response.text().catch(() => "");
      console.log(pc.yellow(`[mtp] Could not enable MTP: HTTP ${response.status} ${detail}`));
    }
  } catch (err) {
    console.log(pc.yellow(`[mtp] Could not enable MTP: ${err.message}`));
  }
}

async function writeManagedState(profile, backend) {
  const state = {
    pid: null,
    profileId: profile.id,
    baseUrl: profile.baseUrl,
    managedBy: backend.id,
    startedAt: new Date().toISOString(),
  };
  await writeState(profile.id, state);
  return state;
}

// ── Stop server ────────────────────────────────────────────────────────────

export async function stopProfile(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") {
    return { stopped: false, message: `${backend.label} is a managed service — offgrid-ai does not stop it.` };
  }
  const state = await readState(profile.id);
  if (!state?.pid) return { stopped: false, message: `No tracked pid for ${profile.id}.` };
  if (!pidAlive(state.pid)) {
    await writeState(profile.id, { ...state, pid: null, stoppedAt: new Date().toISOString(), stopReason: "pid-not-running" });
    return { stopped: false, message: `${profile.id} pid ${state.pid} is no longer running.` };
  }
  const pid = state.pid;
  try {
    const signal = await terminateProcess(pid);
    await writeState(profile.id, { ...state, pid: null, stoppedAt: new Date().toISOString(), stopSignal: signal });
    return { stopped: true, message: `Stopped ${profile.id} pid ${pid}` };
  } catch (error) {
    return { stopped: false, message: `Could not stop pid ${pid}: ${error.message}` };
  }
}

// Reliably terminate a detached local-server process group: SIGTERM with a
// grace period for graceful shutdown, then SIGKILL if still alive.
async function terminateProcess(pid) {
  const signalGroup = (sig) => {
    try { process.kill(-pid, sig); }
    catch { process.kill(pid, sig); } // not a group leader — kill the proc itself
  };
  signalGroup("SIGTERM");
  for (let i = 0; i < 50; i++) { // 5s grace for graceful shutdown
    if (await processGone(pid)) return "SIGTERM";
    await sleep(100);
  }
  signalGroup("SIGKILL");
  for (let i = 0; i < 30; i++) { // 3s for SIGKILL to take effect
    if (await processGone(pid)) return "SIGKILL";
    await sleep(100);
  }
  throw new Error(`pid ${pid} did not exit after SIGKILL`);
}

// True if the process is dead (or a zombie about to be reaped).
async function processGone(pid) {
  try { process.kill(pid, 0); }
  catch { return true; } // no such process
  // Alive to signal(0) — but a detached setsid child can briefly appear as a
  // zombie before launchd reaps it. Treat zombie as gone.
  try {
    const { stdout } = await execFileAsync("ps", ["-o", "stat=", "-p", String(pid)]);
    return /^Z/.test(stdout.trim());
  } catch {
    return false;
  }
}

// ── Unload model from a managed server (oMLX) ─────────────────────────────
// Counterpart to stopProfile for local-server backends: stopProfile kills the
// server process (which unloads the model); unloadModelFromServer asks a
// managed server to release the model from memory via its HTTP API, leaving the
// server itself running. Together they give a consistent UX: quitting Pi
// unloads the model regardless of backend type.

export async function unloadModelFromServer(profile) {
  const backend = backendFor(profile.backend);

  if (backend.id === "llama-cpp") {
    return { unloaded: false, backend: backend.id, reason: "stop server to unload" };
  }

  if (backend.id === "omlx") {
    return await unloadOmlxModel(profile);
  }

  return { unloaded: false, backend: backend.id, reason: "unsupported backend" };
}

async function unloadOmlxModel(profile) {
  const baseUrl = profile.baseUrl?.replace(/\/v1\/?$/u, "") || "";
  const adminUrl = `${baseUrl}/admin/api/models`;
  const modelId = profile.modelAlias || profile.omlxModel || profile.id;

  try {
    const ids = await serverModelIds(profile.baseUrl);
    const match = ids.find((id) => id.toLowerCase() === modelId.toLowerCase());
    const targetId = match ?? modelId;

    const response = await fetch(`${adminUrl}/${encodeURIComponent(targetId)}/unload`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: AbortSignal.timeout(30000),
    });

    if (response.ok) {
      return { unloaded: true, backend: "omlx", modelId: targetId };
    }

    const detail = await responseErrorDetail(response);

    if (response.status === 400 && /not loaded/i.test(detail)) {
      return { unloaded: true, backend: "omlx", modelId: targetId, reason: "model was not loaded" };
    }

    if (response.status === 401 || response.status === 403) {
      return {
        unloaded: false,
        backend: "omlx",
        modelId: targetId,
        error: "oMLX admin authentication required. Enable skip_api_key_verification in oMLX settings, or unload manually from the admin panel.",
      };
    }

    return { unloaded: false, backend: "omlx", modelId: targetId, error: `HTTP ${response.status}: ${detail}` };
  } catch (err) {
    if (err?.name === "AbortError" || err?.name === "TimeoutError") {
      return { unloaded: false, backend: "omlx", modelId, error: "Unload request timed out. The model may still be unloading in the background." };
    }
    return { unloaded: false, backend: "omlx", modelId, error: err.message };
  }
}

async function responseErrorDetail(response) {
  const text = await response.text().catch(() => "");
  if (!text) return "";
  try {
    const body = JSON.parse(text);
    return body?.detail ?? body?.message ?? text;
  } catch {
    return text;
  }
}

// ── Status checks ──────────────────────────────────────────────────────────

export async function isProfileRunning(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") {
    return await serverReady(profile.baseUrl) && (await modelLoadedOnServer(profile));
  }
  const state = await readState(profile.id);
  return Boolean(state?.pid && pidAlive(state.pid));
}

export async function isProfileServerUp(profile) {
  return await serverReady(profile.baseUrl);
}

export async function modelLoadedOnServer(profile) {
  const backend = backendFor(profile.backend);
  if (backend.id === "omlx") return modelIdsMatch(await omlxLoadedModelIds(profile), expectedModelIds(profile));
  const { matches } = await serverMatchesProfile(profile);
  return matches;
}

export async function modelAvailableOnServer(profile) {
  const backend = backendFor(profile.backend);
  if (backend.id === "omlx") {
    // /v1/models lists discovered models; an ID must exist there to be usable.
    return modelIdsMatch(await serverModelIds(profile.baseUrl), expectedModelIds(profile));
  }
  // Local servers are tied to a specific model file via their command argv.
  return true;
}

export async function profileRuntimeStatus(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") {
    const ready = await serverReady(profile.baseUrl);
    const [modelLoaded, modelAvailable] = ready
      ? await Promise.all([modelLoadedOnServer(profile), modelAvailableOnServer(profile)])
      : [false, false];
    return { state: null, pid: null, running: ready && modelLoaded, ready, serverUp: ready, modelLoaded, modelAvailable, rssBytes: null, startedAt: null };
  }
  const state = await readState(profile.id);
  const running = Boolean(state?.pid && pidAlive(state.pid));
  const [ready, rssBytes] = await Promise.all([
    serverReady(profile.baseUrl),
    running ? pidRssBytes(state.pid) : Promise.resolve(null),
  ]);
  return { state, pid: state?.pid ?? null, running, ready, rssBytes, startedAt: state?.startedAt ? new Date(state.startedAt) : null };
}

export async function serverReady(baseUrl) {
  try {
    const response = await fetch(`${baseUrl.replace(/\/$/, "")}/models`, { signal: AbortSignal.timeout(1000) });
    return response.ok;
  } catch {
    return false;
  }
}

export async function serverMatchesProfile(profile) {
  const state = await readState(profile.id);
  if (state?.pid && pidAlive(state.pid) && state.baseUrl === profile.baseUrl) {
    return { matches: true, reason: "tracked offgrid-ai server" };
  }

  const ids = await serverModelIds(profile.baseUrl);
  const expected = expectedModelIds(profile);
  const normalizedIds = new Set(ids.map((id) => id.toLowerCase()));
  if (ids.length > 0 && expected.some((id) => normalizedIds.has(id.toLowerCase()))) {
    return { matches: true, reason: `server reports ${ids.join(", ")}` };
  }

  return {
    matches: false,
    reason: ids.length > 0
      ? `server reports ${ids.join(", ")}; expected ${expected.join(" or ")}`
      : "server is untracked and did not report a recognizable model id",
  };
}

export async function waitForReady(profile, pid, rawLogPath) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") return;
  for (let i = 0; i < 180; i++) {
    if (await serverReady(profile.baseUrl)) return;
    if (pid && !pidAlive(pid)) {
      const tail = await readFile(rawLogPath, "utf8").catch(() => "");
      throw new Error(`llama-server exited early. Last log lines:\n${tail.split(/\r?\n/).slice(-20).join("\n")}`);
    }
    await sleep(1000);
  }
  throw new Error(`Timed out waiting for ${profile.baseUrl}/models`);
}

// ── Internals ──────────────────────────────────────────────────────────────

export async function serverModelIds(baseUrl) {
  const result = await fetchJson(`${baseUrl.replace(/\/+$/u, "")}/models`);
  if (!result.ok) return [];
  return (Array.isArray(result.data?.data) ? result.data.data : [])
    .map((model) => String(model?.id ?? "").trim())
    .filter(Boolean);
}

async function omlxLoadedModelIds(profile) {
  const statusResult = await fetchJson(`${profile.baseUrl.replace(/\/+$/u, "")}/models/status`);
  const fromStatus = statusResult.ok
    ? (Array.isArray(statusResult.data?.models) ? statusResult.data.models : [])
        .filter((model) => model?.loaded === true)
        .flatMap((model) => [model?.id, model?.name, model?.model, model?.alias])
        .map((id) => String(id ?? "").trim())
        .filter(Boolean)
    : [];
  if (!statusResult.ok || Number(statusResult.data?.loaded_count) === 0) return fromStatus;

  const summaryResult = await fetchJson(`${apiRootUrl(profile.baseUrl)}/api/status`);
  const fromSummary = summaryResult.ok
    ? (Array.isArray(summaryResult.data?.loaded_models) ? summaryResult.data.loaded_models : [])
        .map((id) => String(id ?? "").trim())
        .filter(Boolean)
    : [];
  return [...fromStatus, ...fromSummary];
}

async function fetchJson(url) {
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(1000) });
    if (!response.ok) return { ok: false, reason: "http", status: response.status, data: null };
    const data = await response.json();
    return { ok: true, data };
  } catch (error) {
    if (error?.name === "AbortError" || error?.name === "TimeoutError") return { ok: false, reason: "timeout", data: null };
    return { ok: false, reason: "network", data: null };
  }
}

export function apiRootUrl(baseUrl) {
  try {
    const url = new URL(baseUrl);
    url.pathname = url.pathname.replace(/\/v1\/?$/u, "") || "/";
    url.search = "";
    url.hash = "";
    return url.toString().replace(/\/$/u, "");
  } catch {
    return String(baseUrl).replace(/\/v1\/?$/u, "").replace(/\/$/u, "");
  }
}

function modelIdsMatch(actualIds, expectedIds) {
  const actual = normalizedModelIds(actualIds);
  const expected = normalizedModelIds(expectedIds);
  return [...expected].some((id) => actual.has(id));
}

function normalizedModelIds(ids) {
  const normalized = new Set();
  for (const id of ids) {
    const value = normalizeModelId(id);
    if (!value) continue;
    normalized.add(value);
    if (value.endsWith(":latest")) normalized.add(value.slice(0, -":latest".length));
  }
  return normalized;
}

function normalizeModelId(id) {
  return String(id ?? "").trim().toLowerCase();
}

function expectedModelIds(profile) {
  const fileName = profile.modelPath ? basename(profile.modelPath) : null;
  return [
    profile.modelAlias,
    profile.label,
    profile.omlxModel,
    profile.modelPath,
    fileName,
    fileName ? fileName.replace(/\.gguf$/iu, "") : null,
  ].filter(Boolean).map(String);
}

function pidAlive(pid) {
  try { process.kill(pid, 0); return true; }
  catch { return false; }
}

async function pidRssBytes(pid) {
  try {
    const { stdout } = await execFileAsync("ps", ["-o", "rss=", "-p", String(pid)]);
    const rssKb = Number(stdout.trim().split(/\s+/)[0]);
    return Number.isFinite(rssKb) ? rssKb * 1024 : null;
  } catch { return null; }
}

function timestampForFile() {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function quoteShell(value) {
  const text = String(value);
  return /^[A-Za-z0-9_/@%+=:,.-]+$/u.test(text) ? text : `'${text.replace(/'/gu, ` '"'"'`)}'`;
}