import { backendFor, backendBinaryFor } from "./backends.mjs";
import { computeFlags } from "./autodetect.mjs";
import { mtpEnabledFor } from "./capabilities.mjs";

// ── Compute server command from profile config ─────────────────────────────
// Single source of truth: derives the full command (binary + args + env) from
// the profile's stored configuration.  Used for both launching and display so
// they always match.  No stored commandArgv — the command is always fresh.

export async function computeServerCommand(profile) {
  const backend = backendFor(profile.backend);
  if (backend.type === "managed-server") return null;

  const binary = await backendBinaryFor(profile.backend);
  if (!binary) throw new Error("Server binary not found. Run minimal-ai interactively to install.");

  // llama.cpp. Pass choice-resolved capabilities: thinking reflects the
  // configured flags (a user who disabled thinking keeps it off — raw facts
  // would re-add chat_template_kwargs), MTP reflects the mtpEnabled choice.
  const caps = profile.capabilities ?? {};
  const result = computeFlags(
    {
      ...caps,
      thinking: caps.thinking && Boolean(profile.flags?.chatTemplateKwargs),
      mtp: mtpEnabledFor(profile),
    },
    profile.modelPath,
    profile.mmprojPath,
    profile.drafterPath,
    profile.flags ?? {},
  );

  return { binary, argv: result.argv, extraEnv: {}, backend };
}

/** Build a runnable start.sh script for the profile. */
export function buildStartScript(profile, command) {
  const { binary, argv, extraEnv } = command;
  const backend = backendFor(profile.backend);
  const lines = [
    "#!/bin/bash",
    `# Generated by minimal-ai — do not edit`,
    `# Profile: ${String(profile.label).replace(/[\r\n]+/gu, " ")}`,
    `# Backend: ${backend.label}`,
  ];
  for (const [key, value] of Object.entries(extraEnv)) {
    lines.push(`export ${key}="${value}"`);
  }
  lines.push(""); // blank line before exec
  // Format the exec command with backslash continuation
  lines.push(`exec ${quoteShell(binary)} \\`);
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    const hasValue = arg.startsWith("--") && next && !next.startsWith("--");
    if (hasValue) {
      lines.push(`  ${arg} ${quoteShell(next)}${i + 2 < argv.length ? " \\" : ""}`);
      i += 1;
    } else {
      lines.push(`  ${arg}${i + 1 < argv.length ? " \\" : ""}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function timestampForFile() {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");
}

/** Shell-quote one word; exported for the hub's terminal-script generator. */
export function quoteShell(value) {
  const text = String(value);
  return /^[A-Za-z0-9_/@%+=:,.-]+$/u.test(text) ? text : `'${text.replace(/'/gu, ` '"'"'`)}'`;
}